Preprocessing dataset

## **Preprocessing dataset**

In [ ]:
pip install opendatasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import opendatasets as od
  
od.download(
    "https://www.kaggle.com/datasets/burak3ergun/loan-data-set")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: hero1310
Your Kaggle Key: ··········


100%|██████████| 7.80k/7.80k [00:00<00:00, 3.01MB/s]

In [ ]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import jaccard_score
from sklearn.metrics import log_loss

In [ ]:
loan_data = pd.read_csv("/content/loan-data-set/loan_data_set.csv")
loan_data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [ ]:
df = pd.DataFrame(loan_data)

In [ ]:
drop_col = ["Married", "Dependents", "Property_Area", "Loan_ID"]
update_df = df.drop(labels = drop_col,axis=1)
update_df

Gender     Education Self_Employed  ApplicantIncome  CoapplicantIncome  \
0      Male      Graduate            No             5849                0.0   
1      Male      Graduate            No             4583             1508.0   
2      Male      Graduate           Yes             3000                0.0   
3      Male  Not Graduate            No             2583             2358.0   
4      Male      Graduate            No             6000                0.0   
..      ...           ...           ...              ...                ...   
609  Female      Graduate            No             2900                0.0   
610    Male      Graduate            No             4106                0.0   
611    Male      Graduate            No             8072              240.0   
612    Male      Graduate            No             7583                0.0   
613  Female      Graduate           Yes             4583                0.0   

     LoanAmount  Loan_Amount_Term  Credit_History Loan_Status  
0           NaN             360.0             1.0           Y  
1         128.0             360.0             1.0           N  
2          66.0             360.0             1.0           Y  
3         120.0             360.0             1.0           Y  
4         141.0             360.0             1.0           Y  
..          ...               ...             ...         ...  
609        71.0             360.0             1.0           Y  
610        40.0             180.0             1.0           Y  
611       253.0             360.0             1.0           Y  
612       187.0             360.0             1.0           Y  
613       133.0             360.0             0.0           N  

[614 rows x 9 columns]

# Clean data

In [ ]:
update_df = update_df.dropna()

In [ ]:
le = preprocessing.LabelEncoder()
le_gender = le.fit(["Male","Female"])
update_df["Gender"] = le_gender.transform(update_df["Gender"])

le_edu = le.fit(["Graduate","Not Graduate"])
update_df["Education"] = le_edu.transform(update_df["Education"])

le_se = le.fit(["No","Yes"])
update_df["Self_Employed"] = le_se.transform(update_df["Self_Employed"])

le_ls = le.fit(["N","Y"])
update_df["Loan_Status"] = le_ls.transform(update_df["Loan_Status"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

In [ ]:
y = update_df["Loan_Status"]
update_df = update_df.drop(["Loan_Status"],axis = 1)

In [ ]:
update_df

Gender  Education  Self_Employed  ApplicantIncome  CoapplicantIncome  \
1         1          0              0             4583             1508.0   
2         1          0              1             3000                0.0   
3         1          1              0             2583             2358.0   
4         1          0              0             6000                0.0   
5         1          0              1             5417             4196.0   
..      ...        ...            ...              ...                ...   
609       0          0              0             2900                0.0   
610       1          0              0             4106                0.0   
611       1          0              0             8072              240.0   
612       1          0              0             7583                0.0   
613       0          0              1             4583                0.0   

     LoanAmount  Loan_Amount_Term  Credit_History  
1         128.0             360.0             1.0  
2          66.0             360.0             1.0  
3         120.0             360.0             1.0  
4         141.0             360.0             1.0  
5         267.0             360.0             1.0  
..          ...               ...             ...  
609        71.0             360.0             1.0  
610        40.0             180.0             1.0  
611       253.0             360.0             1.0  
612       187.0             360.0             1.0  
613       133.0             360.0             0.0  

[492 rows x 8 columns]

In [ ]:
update_df = preprocessing.StandardScaler().fit(update_df).transform(update_df)
update_df[0:5]

array([[ 0.46671381, -0.50824406, -0.39704793, -0.13381782, -0.02247126,
        -0.20669361,  0.26592316,  0.42409446],
       [ 0.46671381, -0.50824406,  2.51858762, -0.41656225, -0.60458381,
        -0.98547101,  0.26592316,  0.42409446],
       [ 0.46671381,  1.96755867, -0.39704793, -0.49104388,  0.30564257,
        -0.30718102,  0.26592316,  0.42409446],
       [ 0.46671381, -0.50824406, -0.39704793,  0.11927684, -0.60458381,
        -0.04340157,  0.26592316,  0.42409446],
       [ 0.46671381, -0.50824406,  2.51858762,  0.01514544,  1.01514049,
         1.53927509,  0.26592316,  0.42409446]])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(update_df, y, test_size=0.3, random_state=4)
print("Train set: ", X_train.shape, y_train.shape)
print("Test set: ", X_test.shape, y_test.shape)


Train set:  (344, 8) (344,)
Test set:  (148, 8) (148,)


# MODELS

**Logistic Regression Model**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver="newton-cg").fit(X_train, y_train)
LR

LogisticRegression(C=0.01, solver='newton-cg')

In [ ]:
yhat_LR = LR.predict(X_test)
yhat_LR

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
yhat_LR_prob = LR.predict_proba(X_test)

In [ ]:
# Evaluation
[jaccard_score(y_test, yhat_LR, pos_label=1), f1_score(y_test, yhat_LR, average="weighted"),log_loss(y_test, yhat_LR_prob)]

[0.7596899224806202, 0.7599032666069632, 0.5469293708315359]

**SVM Model**

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel = "sigmoid").fit(X_train, y_train)
clf

SVC(kernel='sigmoid')

In [ ]:
yhat_SVM = clf.predict(X_test)
yhat_SVM

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#Evaluation
[jaccard_score(y_test, yhat_LR, pos_label=1), f1_score(y_test, yhat_LR, average="weighted")]

[0.7596899224806202, 0.7599032666069632]

**Decision Tree Model**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dcs = DecisionTreeClassifier(criterion="entropy").fit(X_train, y_train)
dcs

DecisionTreeClassifier(criterion='entropy')

In [ ]:
ytree_dcs = dcs.predict(X_test)
ytree_dcs

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, ytree_dcs))

DecisionTrees's Accuracy:  0.7432432432432432


K-Nearest-neighbors Model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
Ks = 20
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))

for n in range(1,Ks):
  neigh = KNeighborsClassifier( n_neighbors= n).fit(X_train, y_train)
  yhat_neighs = neigh.predict(X_test)
  mean_acc[n-1] = metrics.accuracy_score(y_test, yhat_neighs)

  std_acc[n-1] = np.std(yhat_neighs == y_test) / np.sqrt(yhat_neighs.shape[0])

mean_acc
# its metrics is similar with any K

array([0.72972973, 0.68918919, 0.74324324, 0.71621622, 0.79054054,
       0.7972973 , 0.7972973 , 0.7972973 , 0.7972973 , 0.7972973 ,
       0.78378378, 0.78378378, 0.78378378, 0.79054054, 0.78378378,
       0.79054054, 0.78378378, 0.78378378, 0.78378378])

In [ ]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1) 

The best accuracy was with 0.7972972972972973 with k= 6
